# docker-compose.yml
version: "3.3"

services:
    dynamodb-local:
        image: amazon/dynamodb-local
        hostname: dynamodb
        networks:
          - fsharp-dynamodb-network

    fsharp-devcontainer:
        build:  
            context: .
            dockerfile: Dockerfile
        hostname: fsharp-devcontainer
        command: /bin/sh -c "while sleep 1000; do :; done"
        volumes:
          # Mounts the project folder to '/workspace'. The target path inside the container
          # should match what your application expects. In this case, the compose file is
          # in a sub-folder, so we will mount '..'. You would then reference this path as the
          # 'workspaceFolder' in '.devcontainer/devcontainer.json' so VS Code starts here.
          - ..:/workspace:cached
        user: vscode
        depends_on: 
            - dynamodb-local
        networks:
          - fsharp-dynamodb-network

networks:
  fsharp-dynamodb-network:
    driver: bridge        
